"""Eager domain folder + ``_blueprint.md`` marker (R7.6).

Materializes ``CORTEX/{sanitized_name}/`` on ``create_domain`` so the domain
becomes visible in Obsidian/Syncthing immediately, before the first
``vault_store`` call. The marker file pins the folder and gives the user a
human-readable summary of the blueprint.

Marker filename starts with ``_`` so ``obsidian_sync`` skips it
(see ``_SKIP_PREFIXES`` in ``obsidian/sync.py``).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import structlog

from mycelium.domain.models import DomainBlueprint, slugify
from mycelium.obsidian import frontmatter as fm
from mycelium.vault.storage import _CORTEX

log = structlog.get_logger()

MARKER_NAME = "_blueprint.md"
USER_BLOCK_MARKER = "<!-- user -->"


def cortex_marker_path(vault_root: Path, slug_or_name: str) -> Path:
    """Return ``{vault_root}/CORTEX/{slug}/_blueprint.md``.

    Accepts a slug directly or derives one from a display name — both are
    routed through ``slugify`` to guarantee a single canonical path.
    """
    slug = slugify(slug_or_name)
    return vault_root / _CORTEX / slug / MARKER_NAME


def _path_for_blueprint(vault_root: Path, bp: DomainBlueprint) -> Path:
    slug = bp.slug or slugify(bp.name)
    return vault_root / _CORTEX / slug / MARKER_NAME


def _build_frontmatter(bp: DomainBlueprint) -> dict:
    fields_summary = sorted(bp.tracking.fields.keys()) if bp.tracking.fields else []
    out: dict = {
        "mycelium_blueprint":     True,
        "mycelium_domain":        bp.name,
        "mycelium_slug":          bp.slug or slugify(bp.name),
        "mycelium_synced":        datetime.now(timezone.utc).isoformat(),
    }
    if bp.description:           out["mycelium_description"]        = bp.description
    if bp.anchor_neuron:         out["mycelium_anchor"]             = bp.anchor_neuron
    if bp.anchor_uuid:           out["mycelium_anchor_uuid"]        = bp.anchor_uuid
    if bp.vault_prefix:          out["mycelium_vault_prefix"]       = bp.vault_prefix
    if bp.triggers:              out["mycelium_triggers"]           = list(bp.triggers)
    if bp.extraction.skill:      out["mycelium_extraction_skill"]   = bp.extraction.skill
    if bp.extraction.focus:      out["mycelium_extraction_focus"]   = bp.extraction.focus
    if bp.extraction.neuron_types:
        out["mycelium_neuron_types"] = list(bp.extraction.neuron_types)
    if fields_summary:           out["mycelium_tracking_fields"]    = fields_summary
    return out


def _build_body(bp: DomainBlueprint, user_tail: str = "") -> str:
    lines: list[str] = []
    lines.append(f"# {bp.name}")
    lines.append("")
    if bp.description:
        lines.append(bp.description)
        lines.append("")
    if bp.triggers:
        lines.append("## Triggers")
        for t in bp.triggers:
            lines.append(f"- {t}")
        lines.append("")
    if bp.extraction.skill or bp.extraction.focus or bp.extraction.neuron_types:
        lines.append("## Extraction")
        if bp.extraction.skill:        lines.append(f"- skill: `{bp.extraction.skill}`")
        if bp.extraction.focus:        lines.append(f"- focus: {bp.extraction.focus}")
        if bp.extraction.neuron_types:
            lines.append(f"- neuron types: {', '.join(bp.extraction.neuron_types)}")
        lines.append("")
    if bp.tracking.fields:
        lines.append("## Tracking")
        for fname, fcfg in bp.tracking.fields.items():
            label = fcfg.label or fname
            ref   = f" (ref {fcfg.reference})" if fcfg.reference else ""
            lines.append(f"- **{fname}** — {label}{ref}")
        lines.append("")
    lines.append(
        "<!-- Auto-generated by MYCELIUM. "
        "Edits above the user marker are overwritten on update_domain. -->"
    )
    lines.append("")
    lines.append(USER_BLOCK_MARKER)
    if user_tail:
        if not user_tail.startswith("\n"):
            lines.append("")
        lines.append(user_tail.rstrip("\n"))
    lines.append("")
    return "\n".join(lines)


def _extract_user_tail(existing_text: str) -> str:
    """Return everything after the ``<!-- user -->`` marker (preserved on regen)."""
    idx = existing_text.find(USER_BLOCK_MARKER)
    if idx < 0:
        return ""
    return existing_text[idx + len(USER_BLOCK_MARKER):]


def _atomic_write(path: Path, data: bytes) -> None:
    """Write to a temp file then rename — avoids partial-write corruption."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(data)
    tmp.replace(path)


def render_marker(bp: DomainBlueprint, *, user_tail: str = "") -> str:
    """Compose YAML frontmatter + body. ``user_tail`` is appended after the marker."""
    fmd  = _build_frontmatter(bp)
    body = _build_body(bp, user_tail=user_tail)
    return fm.render(fmd, body)


def ensure_marker(vault_root: Path, bp: DomainBlueprint) -> Path:
    """Idempotent: create folder + marker if missing.

    Does NOT overwrite an existing marker — use ``regenerate_marker`` for that.
    Returns the marker path.
    """
    path = _path_for_blueprint(vault_root, bp)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        log.debug("domain_marker_exists", domain=bp.name, path=str(path))
        return path
    _atomic_write(path, render_marker(bp).encode("utf-8"))
    log.info("domain_marker_created", domain=bp.name, path=str(path))
    return path


def regenerate_marker(vault_root: Path, bp: DomainBlueprint) -> Path:
    """Rewrite YAML+body, preserving the user-block below ``<!-- user -->``.

    If the marker doesn't exist yet, create it (same as ``ensure_marker``).
    """
    path = _path_for_blueprint(vault_root, bp)
    path.parent.mkdir(parents=True, exist_ok=True)
    user_tail = ""
    if path.exists():
        try:
            user_tail = _extract_user_tail(path.read_text(encoding="utf-8"))
        except OSError as e:
            log.warning("domain_marker_read_failed", path=str(path), error=str(e))
    _atomic_write(path, render_marker(bp, user_tail=user_tail).encode("utf-8"))
    log.info("domain_marker_regenerated", domain=bp.name, path=str(path))
    return path
